const books = [
  {number:1,title:'The Pass That Collects',subtitle:'An Old-World Dark Fantasy of Winter Roads and Dark Mercy',asin:'B0GQ6VBHKC',tags:['road'],themes:'winter roads · dark mercy · names as payment',symbol:'△',palette:'linear-gradient(155deg,#29343a,#121619 55%,#050607)'},
  {number:2,title:'The Road That Remembers',subtitle:'An Old-World Dark Fantasy of Haunted Roads and Buried Oaths',asin:'B0GGXK18BR',tags:['road'],themes:'haunted routes · pursuit · buried oaths',symbol:'⌁',palette:'linear-gradient(155deg,#3a3129,#17130f 58%,#070605)'},
  {number:3,title:'The Stone That Keeps Count',subtitle:'An Old-World Gothic Fantasy of Oaths and Salt',asin:'B0GRPRCP17',tags:['road','mercy'],themes:'stone · salt · oaths · physical proof',symbol:'◇',palette:'linear-gradient(155deg,#35372f,#161713 55%,#060706)'},
  {number:4,title:'The Court Above the Hinge',subtitle:'An Old-World Gothic Fantasy of Judgment and Fire',asin:'B0GS75HZY5',tags:['house','mercy'],themes:'judgment · fire · thresholds · burden',symbol:'⊢',palette:'linear-gradient(155deg,#44251d,#1b0e0b 57%,#070403)'},
  {number:5,title:'The Moon That Hunts',subtitle:'An Old-World Dark Fantasy of Blood, Moonlight, and the Hound-King',asin:'B0GSSH5XNG',tags:['road'],themes:'folk horror · moonlight · hound · winter watch',symbol:'◐',palette:'linear-gradient(155deg,#222c3d,#0d121b 58%,#040507)'},
  {number:6,title:'The Cry That Found the Stones',subtitle:'An Old-World Gothic Fantasy of Mourning and Mountain Roads',asin:'B0GTN76D5Y',tags:['road','mercy'],themes:'mourning · denied names · stone memory',symbol:'△',palette:'linear-gradient(155deg,#344048,#161d21 57%,#07090a)'},
  {number:7,title:'The House That Kept the Last Lamp',subtitle:'An Old-World Gothic Fantasy of Deathwatch and False Mercy',asin:'B0GR6J5JJ6',tags:['house','mercy'],themes:'deathwatch · lamp · community · false mercy',symbol:'♢',palette:'linear-gradient(155deg,#3b3020,#1a140b 58%,#080603)'},
  {number:8,title:'The Lady Beneath Midnight',subtitle:'An Old-World Gothic Fantasy of Beauty, Dominion, and False Inheritance',asin:'B0GQ55GPLL',tags:['house','mercy'],themes:'beauty · dominion · inheritance · bodily claim',symbol:'✧',palette:'linear-gradient(155deg,#31243b,#140e1a 58%,#060407)'},
  {number:10,title:'The House That Would Not Release',subtitle:'An Old-World Gothic Fantasy of Wrongful Keeping and Hard-Won Passage',asin:'B0GX33F82R',tags:['house','mercy'],themes:'custody · doors · ledgers · wrongful keeping',symbol:'▥',palette:'linear-gradient(155deg,#263229,#101611 58%,#040605)'},
  {number:14,title:'The Ministry of the Second Dawn',subtitle:'An Old-World Gothic Fantasy of False Mercy, Red Lamps, and Names Returned',asin:'B0GX5488VK',tags:['mercy'],themes:'red lamps · administration · dependency · names returned',symbol:'☼',palette:'linear-gradient(155deg,#47241c,#1b0d09 58%,#080403)'},
  {number:15,title:'The Door of Ninety-Five Nails',subtitle:'An Old-World Gothic Fantasy of Reform, Unheard War, and Sacred Defiance',asin:'B0GZJYJJ1N',tags:['house'],themes:'door · nails · sacred defiance · consequence',symbol:'╫',palette:'linear-gradient(155deg,#35302a,#16130f 58%,#070605)'},
  {number:16,title:'The Twisted Sister',subtitle:'The High Pass Chronicles Book Sixteen',asin:'B0GZQMFYBS',tags:['mercy','house'],themes:'poisoned wedding · vows · mirrors · possession',symbol:'∞',palette:'linear-gradient(155deg,#42252e,#1a0d12 58%,#070405)'},
  {number:17,title:'The Mask That Fed the Rats',subtitle:'An Old-World Gothic Fantasy of Mercy, Hunger, and Erased Names',asin:'B0H34NLK39',tags:['mercy'],themes:'mask · rats · hunger · erased names',symbol:'◉',palette:'linear-gradient(155deg,#32322c,#151510 58%,#050504)'}
];
const grid=document.querySelector('#book-grid'), search=document.querySelector('#book-search'), buttons=[...document.querySelectorAll('.filter-button')], empty=document.querySelector('#no-results'), dialog=document.querySelector('#book-dialog'), dialogContent=document.querySelector('#dialog-content'); let filter='all';
const esc=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function card(b){return `<article class="book-card reveal visible" data-tags="${b.tags.join(' ')}"><div class="book-cover" style="--cover-bg:${b.palette}"><div class="cover-inner"><div class="cover-series">The High Pass Chronicles</div><h3>${esc(b.title)}</h3><div class="cover-symbol" aria-hidden="true">${b.symbol}</div><div class="cover-author">R. Keith Parker</div></div></div><div class="book-meta"><div class="book-order">Book ${b.number}</div><h3>${esc(b.title)}</h3><p>${esc(b.themes)}</p><div class="book-actions"><button type="button" data-book="${b.number}">Details</button><a href="https://www.amazon.com/dp/${b.asin}" target="_blank" rel="noopener">Amazon</a></div></div></article>`}
function render(){const q=search.value.trim().toLowerCase();const shown=books.filter(b=>(filter==='all'||b.tags.includes(filter))&&`${b.title} ${b.subtitle} ${b.themes}`.toLowerCase().includes(q));grid.innerHTML=shown.map(card).join('');empty.hidden=shown.length>0}
function show(n){const b=books.find(x=>x.number===Number(n));if(!b)return;dialogContent.innerHTML=`<div class="dialog-layout"><div class="dialog-cover" style="--cover-bg:${b.palette}"><div><p class="cover-series">The High Pass Chronicles</p><h3>${esc(b.title)}</h3><div class="cover-symbol" aria-hidden="true">${b.symbol}</div><p class="cover-author">R. Keith Parker</p></div></div><div class="dialog-copy"><p class="section-kicker">The High Pass Chronicles · Book ${b.number}</p><h2 id="dialog-title">${esc(b.title)}</h2><p class="dialog-subtitle">${esc(b.subtitle)}</p><div class="dialog-details"><span><strong>Official series number:</strong> Book ${b.number}</span><span><strong>Amazon ASIN:</strong> ${b.asin}</span><span><strong>Core themes:</strong> ${esc(b.themes)}</span></div><a class="button primary" href="https://www.amazon.com/dp/${b.asin}" target="_blank" rel="noopener">Buy on Amazon</a></div></div>`;dialog.showModal()}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-book]');if(b)show(b.dataset.book)});search.addEventListener('input',render);buttons.forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;buttons.forEach(x=>x.classList.toggle('active',x===b));render()}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav.addEventListener('click',e=>{if(e.target.tagName==='A'){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}});window.addEventListener('scroll',()=>document.querySelector('.site-header').classList.toggle('scrolled',scrollY>20),{passive:true});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('#book-schema').textContent=JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:'The High Pass Chronicles',author:{'@type':'Person',name:'R. Keith Parker'},mainEntity:{'@type':'ItemList',itemListElement:books.map((b,i)=>({'@type':'ListItem',position:i+1,item:{'@type':'Book',name:b.title,bookSeries:{'@type':'BookSeries',name:'The High Pass Chronicles'},position:b.number,url:`https://www.amazon.com/dp/${b.asin}`}}))}});render();